feat: add ics file import
JM-Lemmi/ical-relay pull request #232
Opened 2024-02-09 20:43 UTC by nilsfast

Fixes #68

To do: 
- [ ] Add hint in front end that import via DnD is possible

2024-02-09 22:41 UTC, JM-Lemmi commented
Man könnte auch für den "plus" Button unten rechts auch ein "Datei upload" hinzufügen. Und dort einen "wusstest du: es geht auch über drag&drop" hinweis anzeigen, während das File selection Fenster offen ist.

2024-02-09 23:13 UTC, JM-Lemmi requested changes
Does not work on my Device:

Firefox 115.7.0esr; Debian 12

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/8bf86718-8276-4eae-9f5c-6b0e1fe59e94)

No request arrives at the server.

2024-02-09 23:24 UTC, nilsfast commented
@JM-Lemmi vielleicht noch die alte API.js gecached?

2024-02-09 23:36 UTC, JM-Lemmi commented
Nochmal ganz neu gebaut, Firefox geleert und ohne Cache neugeladen, jetzt ist der Fehler tatsächlich ein anderer.

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/c620f0fa-ad73-4fd5-94cc-2939c775c3eb)

2024-02-10 10:39 UTC, nilsfast commented
Mal wieder das alt-bekannte Problem mit den gespeicherten Profiles, die in die URL eingesetzt werden. Es zeigt jetzt einen Fehler im Frontend an.

2024-02-10 10:49 UTC, JM-Lemmi commented
Warum muss denn ein Profil hinterlegt sein?

2024-02-10 10:51 UTC, nilsfast commented
Muss eigentlich nicht. Einfacher wäre wahrscheinlich das zu nehmen, was gerade angezeigt wird.

2024-02-10 10:52 UTC, JM-Lemmi requested changes

2024-02-10 10:52 UTC, JM-Lemmi commented on cmd/ical-relay/templates/static/js/dnd.js
> +            "profiles/" + localStorage.getItem("profile") + "/newentryfile",
hier sollte doch das profil genutzt werden, das gerade im view geöffnet ist. Sonst fügt es den Termin ja immer zum gespeicherten Profil hinzu statt zu dem in dem ich grade bin. Das ist ja mega verwirrend.

2024-02-10 11:30 UTC, JM-Lemmi requested changes
File Size check scheint noch falsch zu sein.

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/c08dbb29-018b-40c1-b473-535254efffff)

Die Fehlermeldung im Frontend ist auch nicht sehr aussagekräftig. Hier vielleicht den Status Code und Body aus der Response auch anzeigen? Zumindest als zweite Zeile oder so

![image](https://github.com/JM-Lemmi/ical-relay/assets/41118534/babdc2a2-785a-42e0-ab08-17d508aabaf1)

Die Response enthält ja den korrekten Code und im Body den Fehler

2024-02-10 11:31 UTC, JM-Lemmi commented
Je länger ich überlege, desto eher ist der File Size check an dieser Stelle sowieso quatsch. Die Begrenzung sollte technische limits haben, nämlich die postgres größe. Alles andere wird von der WAF/dem Proxy erledigt.

2024-02-10 11:42 UTC, nilsfast commented
> Die Fehlermeldung im Frontend ist auch nicht sehr aussagekräftig. Hier vielleicht den Status Code und Body aus der Response auch anzeigen? Zumindest als zweite Zeile oder so

So gut ist leider die API Class nicht, ich mache das jetzt über Standard fetch

2024-02-10 12:26 UTC, JM-Lemmi commented
scheint jetzt zu funktionieren, allerdings zeigt das Frontend den neuen Termin nicht an und die ICS bekommt mit jedem Aufruf den Termin ein weiteres mal dazu. Ich denke das ist ein Problem an einer anderen Stelle, aber würde ich eigentlich auch gerne fixen.

2024-02-10 12:39 UTC, JM-Lemmi approved these changes

2024-02-10 12:47 UTC, merged